version: "3.8"

services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - trekie

  trekie-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: trekie
      POSTGRES_PASSWORD: trekie123
      POSTGRES_DB: trekie
    volumes:
      - trekie-db-data:/var/lib/postgresql/data
    networks:
      - trekie

networks:
  trekie:

volumes:
  trekie-db-data:
